// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export const EIP712_LIBRARY_MASM = `use miden::core::crypto::dsa::ecdsa_k256_keccak
use miden::core::crypto::hashes::keccak256
use miden::core::crypto::hashes::poseidon2

# CONSTANTS
# =================================================================================================

# The repeated u32 is the little-endian ASCII encoding of "E712". It domain-separates the
# EIP-712 advice key from the raw-signature key.
const EIP712_SIGNATURE_KEY_DOMAIN=0x32313745

# Local memory layout for verify_transaction_summary:
#   0..16   MidenTransaction struct preimage
#   16..24  MidenTransaction struct hash
#   24..32  Miden Multisig domain separator
#   32..36  public-key commitment
const STRUCT_PREIMAGE_LOC=0
const TX_SUMMARY_LOC=8
const STRUCT_HASH_LOC=16
const STRUCT_HASH_HIGH_LOC=20
const DOMAIN_SEPARATOR_LOC=24
const DOMAIN_SEPARATOR_HIGH_LOC=28
const ADAPTER_PUBLIC_KEY_COMMITMENT_LOC=32

# Local memory layout for verify:
#   0..24   EIP-712 digest preimage, zero-padded to three 32-byte chunks
#   24..28  public-key commitment
#   28..36  domain separator
#   36..44  struct hash
const DIGEST_PREIMAGE_LOC=0
const PUBLIC_KEY_COMMITMENT_LOC=24
const DOMAIN_SEPARATOR_INPUT_LOC=28
const DOMAIN_SEPARATOR_INPUT_HIGH_LOC=32
const STRUCT_HASH_INPUT_LOC=36
const STRUCT_HASH_INPUT_HIGH_LOC=40

# \`keccak256("MidenTransaction(bytes32 txSummaryHash)")\`, packed as little-endian u32 limbs.
const TRANSACTION_TYPE_HASH_0=3002887380
const TRANSACTION_TYPE_HASH_1=1420631288
const TRANSACTION_TYPE_HASH_2=494091842
const TRANSACTION_TYPE_HASH_3=2729528150
const TRANSACTION_TYPE_HASH_4=4274085984
const TRANSACTION_TYPE_HASH_5=2147426208
const TRANSACTION_TYPE_HASH_6=2043519110
const TRANSACTION_TYPE_HASH_7=1663807340

# \`keccak256(abi.encode(
#     keccak256("EIP712Domain(string name,string version)"),
#     keccak256("Miden Multisig"),
#     keccak256("1")
# ))\`, packed as little-endian u32 limbs.
const DOMAIN_SEPARATOR_0=1511125767
const DOMAIN_SEPARATOR_1=3117083882
const DOMAIN_SEPARATOR_2=446958287
const DOMAIN_SEPARATOR_3=2727036186
const DOMAIN_SEPARATOR_4=1195751528
const DOMAIN_SEPARATOR_5=2604681929
const DOMAIN_SEPARATOR_6=2130785247
const DOMAIN_SEPARATOR_7=3903456984

# PROCEDURES
# =================================================================================================

#! Extends a raw transaction-signature advice key into the EIP-712 key domain.
#!
#! Inputs:  [RAW_SIGNATURE_KEY]
#! Outputs: [EIP712_SIGNATURE_KEY]
pub proc extend_signature_key
    push.EIP712_SIGNATURE_KEY_DOMAIN.EIP712_SIGNATURE_KEY_DOMAIN.EIP712_SIGNATURE_KEY_DOMAIN.EIP712_SIGNATURE_KEY_DOMAIN
    swapw
    exec.poseidon2::merge
end

#! Verifies an ECDSA signature over an EIP-712 typed-data digest.
#!
#! The caller supplies the domain separator and struct hash as little-endian u32 limbs, matching
#! \`keccak256::hash_bytes\`.
#!
#! Inputs:
#!   Operand stack: [PK_COMM, DOMAIN_SEPARATOR[8], STRUCT_HASH[8]]
#!   Advice stack:  [QX[8] | QY[8] | SIG_R[8] | SIG_S[8]]
#! Outputs:
#!   Operand stack: []
#!
#! The caller must derive both hashes from trusted state.
@locals(44)
pub proc verify
    loc_storew_le.PUBLIC_KEY_COMMITMENT_LOC dropw
    # => [DOMAIN_SEPARATOR[8], STRUCT_HASH[8]]

    loc_storew_le.DOMAIN_SEPARATOR_INPUT_LOC dropw
    loc_storew_le.DOMAIN_SEPARATOR_INPUT_HIGH_LOC dropw
    loc_storew_le.STRUCT_HASH_INPUT_LOC dropw
    loc_storew_le.STRUCT_HASH_INPUT_HIGH_LOC dropw
    # => []

    # The byte verifier reads full 32-byte chunks, so clear the chunk containing the final two
    # struct-hash bytes and all trailing padding before writing the 66-byte preimage.
    padw locaddr.DIGEST_PREIMAGE_LOC add.16 mem_storew_le dropw
    padw locaddr.DIGEST_PREIMAGE_LOC add.20 mem_storew_le dropw

    # Prefix the domain separator with 0x1901. Every following pair of adjacent u32 limbs is
    # shifted by two bytes to preserve the exact EIP-712 byte layout.
    push.0x0119
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.1 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.1 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.1 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.2 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.2 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.2 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.3 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.3 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.3 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.4 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.4 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.4 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.5 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.5 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.5 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.6 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.6 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.6 mem_load u32shr.16
    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.7 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.7 mem_store

    locaddr.DOMAIN_SEPARATOR_INPUT_LOC add.7 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.8 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.1 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.9 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.1 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.2 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.10 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.2 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.3 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.11 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.3 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.4 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.12 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.4 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.5 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.13 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.5 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.6 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.14 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.6 mem_load u32shr.16
    locaddr.STRUCT_HASH_INPUT_LOC add.7 mem_load push.0xFFFF u32and u32shl.16 u32or
    locaddr.DIGEST_PREIMAGE_LOC add.15 mem_store

    locaddr.STRUCT_HASH_INPUT_LOC add.7 mem_load u32shr.16
    locaddr.DIGEST_PREIMAGE_LOC add.16 mem_store

    # Hash the 66-byte EIP-712 preimage and verify the resulting ECDSA digest.
    push.66 locaddr.DIGEST_PREIMAGE_LOC
    padw loc_loadw_le.PUBLIC_KEY_COMMITMENT_LOC
    exec.ecdsa_k256_keccak::verify_bytes
end

#! Verifies an ECDSA signature over the EIP-712 transaction-summary message.
#!
#! Inputs:
#!   Operand stack: [PK_COMM, TX_SUMMARY_HASH]
#!   Advice stack:  [QX[8] | QY[8] | SIG_R[8] | SIG_S[8]]
#! Outputs:
#!   Operand stack: []
#!
#! The struct hash commits to \`MidenTransaction(bytes32 txSummaryHash)\`. The transaction-summary
#! hash comes from the authentication component, not advice.
@locals(36)
pub proc verify_transaction_summary
    loc_storew_le.ADAPTER_PUBLIC_KEY_COMMITMENT_LOC dropw
    # => [TX_SUMMARY_HASH]

    # Stage \`keccak256("MidenTransaction(bytes32 txSummaryHash)")\`.
    push.TRANSACTION_TYPE_HASH_3.TRANSACTION_TYPE_HASH_2.TRANSACTION_TYPE_HASH_1.TRANSACTION_TYPE_HASH_0
    locaddr.STRUCT_PREIMAGE_LOC mem_storew_le dropw
    push.TRANSACTION_TYPE_HASH_7.TRANSACTION_TYPE_HASH_6.TRANSACTION_TYPE_HASH_5.TRANSACTION_TYPE_HASH_4
    locaddr.STRUCT_PREIMAGE_LOC add.4 mem_storew_le dropw

    # Append TX_SUMMARY_HASH as an EIP-712 bytes32 value.
    locaddr.TX_SUMMARY_LOC movdn.4
    exec.write_word

    # Compute STRUCT_HASH.
    push.64 locaddr.STRUCT_PREIMAGE_LOC
    exec.keccak256::hash_bytes
    locaddr.STRUCT_HASH_LOC mem_storew_le dropw
    locaddr.STRUCT_HASH_LOC add.4 mem_storew_le dropw

    # Stage the fixed Miden Multisig domain separator.
    push.DOMAIN_SEPARATOR_3.DOMAIN_SEPARATOR_2.DOMAIN_SEPARATOR_1.DOMAIN_SEPARATOR_0
    locaddr.DOMAIN_SEPARATOR_LOC mem_storew_le dropw
    push.DOMAIN_SEPARATOR_7.DOMAIN_SEPARATOR_6.DOMAIN_SEPARATOR_5.DOMAIN_SEPARATOR_4
    locaddr.DOMAIN_SEPARATOR_LOC add.4 mem_storew_le dropw

    # Delegate the generic EIP-712 digest construction and ECDSA verification.
    padw loc_loadw_le.STRUCT_HASH_HIGH_LOC
    padw loc_loadw_le.STRUCT_HASH_LOC
    padw loc_loadw_le.DOMAIN_SEPARATOR_HIGH_LOC
    padw loc_loadw_le.DOMAIN_SEPARATOR_LOC
    padw loc_loadw_le.ADAPTER_PUBLIC_KEY_COMMITMENT_LOC
    exec.verify
end

#! Writes a Miden word as the 32-byte EIP-712 bytes32 value at ptr.
#!
#! Inputs:  [W0, W1, W2, W3, ptr]
#! Outputs: []
proc write_word
    swap u32split
    movup.2 u32split
    dup.6 mem_storew_le dropw

    swap u32split
    movup.2 u32split
    dup.4 add.4 mem_storew_le dropw
    drop
end
`;

export const SIGNATURE_LIBRARY_MASM = `use miden::core::crypto::dsa::falcon512_poseidon2
use miden::core::crypto::hashes::poseidon2
use miden::core::crypto::dsa::ecdsa_k256_keccak
use {AUTH_REQUEST_EVENT} from miden::protocol::auth
use miden::protocol::native_account
use miden::standards::auth

# CONSTANTS
# =================================================================================================

# Auth Scheme ID Structure
const ECDSA_K256_KECCAK_SCHEME_ID=1
const FALCON_512_POSEIDON2_SCHEME_ID=2

# Estimated upper bounds on the number of cycles authenticate_transaction takes per signature
# scheme, for use as the num_extra_cycles input of fee::pay_fee. Measured values (see
# bin/bench-transaction/bench-tx.json): ECDSA ~3.7k-4.1k, Falcon ~71.6k-72k. Overestimation is
# cheap: the fee grows with ilog2 of the cycle count, so a <2x overshoot costs at most one
# verification_base_fee unit. Guarded by the fee-payment regression tests.
const ECDSA_K256_KECCAK_AUTH_CYCLES = 8000
const FALCON_512_POSEIDON2_AUTH_CYCLES = 80000

# Estimated upper bound on the number of cycles a multisig authentication flow spends outside of
# per-signature verification: transaction summary creation and hashing, threshold config reads,
# the per-procedure threshold/policy scans and replay-protection recording. The per-procedure
# scans grow with the account's procedure count (bounded by the kernel's maximum), so accounts
# with very many procedures may slightly under-estimate the fee; that fails closed (the batch
# builder may reject the underpaying note) and is largely absorbed by the ilog2-domain fee
# formula. Guarded by the fee-payment regression tests.
const MULTISIG_AUTH_BASE_CYCLES = 8192

# Local Memory Addresses for multisig operations
const APPROVER_PUB_KEY_SLOT_ID_SUFFIX_LOC=0
const APPROVER_PUB_KEY_SLOT_ID_PREFIX_LOC=1
const APPROVER_SCHEME_ID_SLOT_ID_SUFFIX_LOC=2
const APPROVER_SCHEME_ID_SLOT_ID_PREFIX_LOC=3
const SUCCESSFUL_VERIFICATIONS_LOC=4

# ERRORS
# =================================================================================================
const ERR_INVALID_SCHEME_ID = "invalid signature scheme id: expected 2 for falcon512_poseidon2, 1 for ecdsa_k256_keccak"
const ERR_INVALID_SCHEME_ID_WORD = "invalid scheme ID word format expected three zero values followed by the scheme ID"

#! Authenticate a transaction using the signature scheme specified by scheme_id.
#!
#! Supported schemes:
#! - 1 => ecdsa_k256_keccak
#! - 2 => falcon512_poseidon2
#!
#! It first increments the nonce of the account, independent of whether the account's state has
#! changed or not. Then it computes and signs the following message (in memory order):
#! [ACCOUNT_DELTA_COMMITMENT, INPUT_NOTES_COMMITMENT, OUTPUT_NOTES_COMMITMENT,
#!  BLOCK_COMMITMENT, [expiration_delta, final_nonce, 0, 0], [0, 0, 0, 0]]
#!
#! Including the final_nonce is necessary for replay protection. The reference block commitment is
#! included to commit to the transaction creator's intended reference block of the transaction
#! which determines the fee parameters and therefore the fee amount that is deducted. The
#! expiration block delta is included to commit to the transaction's expiration.
#!
#! Inputs:  [PK_COMM, scheme_id]
#! Outputs: []
#!
#! Invocation: exec
pub proc authenticate_transaction
    # Increment the account's nonce.
    # ---------------------------------------------------------------------------------------------
    # This has to happen before computing the delta commitment, otherwise that procedure will abort
    exec.native_account::incr_nonce
    # => [final_nonce, PK_COMM, scheme_id]

    # Pass the final nonce as the first user param and zero the remaining ones.
    push.0.0.0.0.0.0 movup.6
    # => [user_params(7), PK_COMM, scheme_id]

    # Compute the message that is signed. The summary preimage is inserted into the advice map
    # for extraction by the host.
    # ---------------------------------------------------------------------------------------------
    exec.auth::create_tx_summary
    # => [ACCOUNT_DELTA_COMMITMENT, INPUT_NOTES_COMMITMENT, OUTPUT_NOTES_COMMITMENT, BLOCK_COMMITMENT, PARAMS_HEAD, PARAMS_TAIL, PK_COMM, scheme_id]

    exec.auth::hash_and_insert_tx_summary
    # OS => [MESSAGE, PK_COMM, scheme_id]
    # AS => []

    # Fetch signature from advice provider and verify.
    # ---------------------------------------------------------------------------------------------
    # Emit the authentication request event that pushes a signature for the message to the advice stack
    emit.AUTH_REQUEST_EVENT
    swapw
    # OS => [PK_COMM, MESSAGE, scheme_id]
    # AS => [SIGNATURE]

    movup.8
    # OS => [scheme_id, PK_COMM, MESSAGE]
    # AS => [SIGNATURE]

    # Verify the signature against the public key and the message. The procedure gets as inputs the
    # hash of the public key and the message via the operand stack. The signature is provided via
    # the advice stack. The signature is valid if and only if the procedure returns.
    exec.verify_signature_by_scheme
    # OS => []
    # AS => []
end

#! Verifies a signature using the supplied scheme id.
#!
#! Supported schemes:
#! - 1 => ECDSA (ecdsa_k256_keccak)
#! - 2 => Falcon (falcon512_poseidon2)
#!
#! Inputs:  [scheme_id, PK_COMM, MSG]
#! Outputs: []
#!
#! Invocation: exec
pub proc verify_signature_by_scheme
    dup eq.ECDSA_K256_KECCAK_SCHEME_ID
    # => [is_one, scheme_id, PK_COMM, MESSAGE]

    if.true
        drop
        # OS => [PK_COMM, MESSAGE]

        exec.ecdsa_k256_keccak::verify
        # OS => []
        # AS => []
    else
        eq.FALCON_512_POSEIDON2_SCHEME_ID
        # => [is_2, PK_COMM, MESSAGE]

        if.true
            # OS => [PK_COMM, MESSAGE]

            exec.falcon512_poseidon2::verify
            # OS => []
            # AS => []
        else
            # ------ Invalid Scheme ID ------
            push.0 assert.err=ERR_INVALID_SCHEME_ID
        end
    end
end

#! Returns a conservative upper bound on the number of cycles authenticate_transaction takes for
#! the given signature scheme.
#!
#! Intended to be passed as the num_extra_cycles input of fee::pay_fee when fee payment happens
#! right before authenticate_transaction. Unknown scheme ids return the largest bound; the
#! authentication itself aborts on them later.
#!
#! Inputs:  [scheme_id]
#! Outputs: [num_cycles]
#!
#! Where:
#! - scheme_id is the signature scheme id (1 for ecdsa_k256_keccak, 2 for falcon512_poseidon2).
#! - num_cycles is the estimated upper bound on authenticate_transaction's cycle count.
#!
#! Invocation: exec
pub proc estimate_authentication_cycles
    eq.ECDSA_K256_KECCAK_SCHEME_ID
    # => [is_ecdsa]

    push.FALCON_512_POSEIDON2_AUTH_CYCLES push.ECDSA_K256_KECCAK_AUTH_CYCLES
    # => [ecdsa_cycles, falcon_cycles, is_ecdsa]

    movup.2 cdrop
    # => [num_cycles]
end

#! Returns a conservative upper bound on the number of cycles a multisig authentication flow
#! takes when up to num_of_signers signatures are verified.
#!
#! Intended to be passed as the num_extra_cycles input of fee::pay_fee when fee payment happens
#! right before the multisig authentication flow (summary creation, signature verification and
#! replay-protection recording). Signature verification runs at most once per signer and every
#! supported scheme's verification cost is bounded by the Falcon estimate (the most expensive
#! scheme), so the bound is num_of_signers * FALCON_512_POSEIDON2_AUTH_CYCLES plus a base margin
#! covering the rest of the flow.
#!
#! Approvers within one account may use different schemes (hybrid multisig): each approver's
#! scheme id lives in a per-signer storage map that verify_signatures reads inside its loop, so
#! there is no single per-account scheme to parameterize the estimate with (unlike
#! estimate_authentication_cycles for singlesig). Summing per-signer estimates upfront would
#! duplicate those map reads at a cost that itself grows with the approver count, so the bound
#! conservatively assumes the most expensive scheme for every signer instead. This is a
#! per-signer worst case: a multisig with many approvers but a low threshold, or one using the
#! cheaper ECDSA scheme, only verifies a few (cheaper) signatures, so the estimate can overshoot
#! the real cost by roughly the approver-to-verified ratio. Overestimation only ever raises the
#! fee, and because the fee grows with ilog2 of the cycle count each doubling of the overshoot
#! costs at most one extra verification_base_fee unit, so even a 10x overshoot costs only a few
#! fee units.
#!
#! Inputs:  [num_of_signers]
#! Outputs: [num_cycles]
#!
#! Where:
#! - num_of_signers is the maximum number of signature verifications the authentication flow can
#!   perform (e.g. the number of approvers).
#! - num_cycles is the estimated upper bound on the authentication flow's cycle count.
#!
#! Invocation: exec
pub proc estimate_multisig_authentication_cycles
    mul.FALCON_512_POSEIDON2_AUTH_CYCLES add.MULTISIG_AUTH_BASE_CYCLES
    # => [num_cycles]
end

#! Returns 1 if scheme_id is supported, else 0.
#! Inputs:  [scheme_id]
#! Outputs: [is_supported]
#!
#! Invocation: exec
pub proc is_supported_scheme
    dup eq.ECDSA_K256_KECCAK_SCHEME_ID
    # => [is_1, scheme_id]

    swap eq.FALCON_512_POSEIDON2_SCHEME_ID
    # => [is_2, is_1]

    or
    # => [is_supported]
end

#! Reverts if scheme_id is not supported.
#! Inputs:  [scheme_id]
#! Outputs: []
#!
#! Invocation: exec
pub proc assert_supported_scheme
    exec.is_supported_scheme
    # => [is_supported]

    assert.err=ERR_INVALID_SCHEME_ID
    # => []
end


#! Validates scheme id word shape: [scheme_id, 0, 0, 0]
#! Inputs:  [SCHEME_ID_WORD]
#! Outputs: [SCHEME_ID_WORD]
#!
#! Invocation: exec
pub proc assert_supported_scheme_word
    dupw exec.assert_supported_scheme
    # => [0, 0, 0, SCHEME_ID_WORD]

    assertz.err=ERR_INVALID_SCHEME_ID_WORD
    assertz.err=ERR_INVALID_SCHEME_ID_WORD
    assertz.err=ERR_INVALID_SCHEME_ID_WORD
    # => [SCHEME_ID_WORD]
end


#! Verify signatures for all required signers in a loop.
#!
#! This procedure iterates through the required number of signers, fetches their public keys from
#! the provided account storage map slot, verifies their signatures against the transaction message,
#! and returns the number of successfully verified signatures.
#!
#! Note: Calls \`native_account::get_initial_map_item\` to access the transaction's initial storage
#! state rather than the current state. This is crucial when validating transactions that update
#! the owner public key mapping - the previous signers must authorize the change to the new signers,
#! not the new signers authorizing themselves.
#!
#! Inputs:  [approver_scheme_id_slot_id_suffix, approver_scheme_id_slot_id_prefix,
#!           approver_pub_key_slot_id_suffix, approver_pub_key_slot_id_prefix,
#!           num_of_approvers, MSG]
#! Outputs: [num_verified_signatures, MSG]
#!
#! Invocation: exec
@locals(5)
pub proc verify_signatures
    loc_store.APPROVER_SCHEME_ID_SLOT_ID_SUFFIX_LOC
    loc_store.APPROVER_SCHEME_ID_SLOT_ID_PREFIX_LOC
    # => [approver_pub_key_slot_id_suffix, approver_pub_key_slot_id_prefix, num_of_approvers, MSG]

    loc_store.APPROVER_PUB_KEY_SLOT_ID_SUFFIX_LOC
    loc_store.APPROVER_PUB_KEY_SLOT_ID_PREFIX_LOC
    # => [num_of_approvers, MSG]

    # Initializing SUCCESSFUL_VERIFICATIONS local memory address to 0
    push.0 loc_store.SUCCESSFUL_VERIFICATIONS_LOC
    # => [num_of_approvers, MSG]

    # Counter \`i\` starts at \`num_of_approvers\` and counts down to 0
    # => [i, MSG]

    # Loop through required signers and verify signatures.
    # ---------------------------------------------------------------------------------------------

    dup neq.0
    while.true
        # => [i, MSG]

        # Fetch public key from storage map.
        # -----------------------------------------------------------------------------------------

        sub.1 dup
        # => [signer_idx, signer_idx, MSG]

        exec.create_approver_map_key
        # => [APPROVER_MAP_KEY, signer_idx, MSG]

        # Get public key from initial storage state
        loc_load.APPROVER_PUB_KEY_SLOT_ID_PREFIX_LOC
        loc_load.APPROVER_PUB_KEY_SLOT_ID_SUFFIX_LOC
        exec.native_account::get_initial_map_item
        # => [PK_COMM, signer_idx, MSG]

        # Check if signature exists for this signer.
        # -----------------------------------------------------------------------------------------

        movup.4 movdn.8
        # => [PK_COMM, MSG, signer_idx]

        dupw.1 dupw.1
        # => [PK_COMM, MSG, PK_COMM, MSG, signer_idx]

        exec.poseidon2::merge
        # => [SIG_KEY, PK_COMM, MSG, signer_idx]

        adv.has_mapkey
        # => [SIG_KEY, PK_COMM, MSG, signer_idx]

        dropw
        # => [PK_COMM, MSG, signer_idx]

        adv_push
        # => [has_signature, PK_COMM, MSG, signer_idx]

        # if a signature for this signer exists in the advice map, verify it
        if.true
            # => [PK_COMM, MSG, signer_idx]

            dupw.1
            # => [MSG, PK_COMM, MSG, signer_idx]

            # Verify the signature against the public key and message.
            # -----------------------------------------------------------------------------------------

            # Emit the authentication request event that pushes a signature for the message to the advice stack.
            emit.AUTH_REQUEST_EVENT
            # => [MSG, PK_COMM, MSG, signer_idx]

            swapw
            # => [PK_COMM, MSG, MSG, signer_idx]

            dup.12 exec.create_approver_map_key
            # => [APPROVER_MAP_KEY, PK_COMM, MSG, MSG, signer_idx]

            loc_load.APPROVER_SCHEME_ID_SLOT_ID_PREFIX_LOC loc_load.APPROVER_SCHEME_ID_SLOT_ID_SUFFIX_LOC
            # => [scheme_slot_id_suffix, scheme_slot_id_prefix, APPROVER_MAP_KEY, PK_COMM, MSG, MSG, signer_idx]

            # Get scheme_id for the signer index from initial storage state.
            exec.native_account::get_initial_map_item
            # => [[scheme_id, 0, 0, 0], PK_COMM, MSG, MSG, signer_idx]

            movdn.3 drop drop drop
            # OS => [scheme_id, PK_COMM, MSG, MSG, signer_idx]
            # AS => [SIGNATURE]

            exec.verify_signature_by_scheme
            # => [MSG, signer_idx]

            loc_load.SUCCESSFUL_VERIFICATIONS_LOC
            add.1
            loc_store.SUCCESSFUL_VERIFICATIONS_LOC
            # => [MSG, signer_idx]
        else
            dropw
            # => [MSG, signer_idx]
        end
        # => [MSG, signer_idx]

        movup.4
        # => [signer_idx, MSG]

        dup neq.0
        # => [should_continue, signer_idx, MSG]
    end
    # => [signer_idx, MSG]

    # Return successful signature verifications along with MSG
    # -----------------------------------------------------------------------------------------

    drop
    # => [MSG]

    loc_load.SUCCESSFUL_VERIFICATIONS_LOC
    # => [num_verified_signatures, MSG]
end

#! Builds the storage map key for a signer index.
#!
#! Inputs: [key_index]
#! Outputs: [APPROVER_MAP_KEY]
#!
#! Invocation: exec
pub proc create_approver_map_key
    push.0.0.0 movup.3
    # => [APPROVER_MAP_KEY]
end
`;

export const MULTISIG_LIBRARY_MASM = `# The MASM code of the Multi-Signature Authentication Component.
#
# See the \`AuthMultisig\` Rust type's documentation for more details.

use miden::protocol::active_account
use {AUTH_REQUEST_EVENT, AUTH_UNAUTHORIZED_EVENT} from miden::protocol::auth
use miden::protocol::native_account
use miden::standards::auth
use guardian_sdk::auth::eip712
use guardian_sdk::auth::signature
use miden::core::crypto::hashes::poseidon2
use miden::core::word
use {ONE_WORD} from miden::standards::utils

# Local Memory Addresses
const IS_SIGNER_FOUND_LOC=0
const CURRENT_SIGNER_INDEX_LOC=1

const NEW_NUM_OF_APPROVERS_LOC=0
const INIT_NUM_OF_APPROVERS_LOC=1

const DEFAULT_THRESHOLD_LOC=0

const UNIQUE_OUTER_INDEX_LOC=0
const UNIQUE_INNER_INDEX_LOC=1

const SUCCESSFUL_VERIFICATIONS_LOC=0

# CONSTANTS
# =================================================================================================

const ECDSA_K256_KECCAK_SCHEME_ID=1

# Storage Slots
#
# This authentication component uses named storage slots.
# - THRESHOLD_CONFIG_SLOT:
#   [default_threshold, num_approvers, 0, 0]
#
# - APPROVER_PUBLIC_KEYS_SLOT (map):
#   APPROVER_MAP_KEY => APPROVER_PUBLIC_KEY
#   where APPROVER_MAP_KEY = [key_index, 0, 0, 0]
#
# - APPROVER_SCHEME_ID_SLOT (map):
#   APPROVER_MAP_KEY => [scheme_id, 0, 0, 0]
#   where APPROVER_MAP_KEY = [key_index, 0, 0, 0]
#
# - EXECUTED_TXS_SLOT (map):
#   TRANSACTION_MESSAGE => [is_executed, 0, 0, 0]
#
# - PROC_THRESHOLD_ROOTS_SLOT (map):
#   PROC_ROOT => [proc_threshold, 0, 0, 0]

# The slot in this component's storage layout where the default signature threshold and
# number of approvers are stored as:
# [default_threshold, num_approvers, 0, 0].
# The threshold is guaranteed to be less than or equal to num_approvers.
pub const THRESHOLD_CONFIG_SLOT = word("miden::standards::auth::multisig::threshold_config")

# The slot in this component's storage layout where the public keys map is stored.
# Map entries: [key_index, 0, 0, 0] => APPROVER_PUBLIC_KEY
pub const APPROVER_PUBLIC_KEYS_SLOT = word("miden::standards::auth::multisig::approver_public_keys")

# The slot in this component's storage layout where the scheme id for the corresponding public keys map is stored.
# Map entries: [key_index, 0, 0, 0] => [scheme_id, 0, 0, 0]
pub const APPROVER_SCHEME_ID_SLOT = word("miden::standards::auth::multisig::approver_schemes")

# The slot in this component's storage layout where executed transactions are stored.
# Map entries: transaction_message => [is_executed, 0, 0, 0]
const EXECUTED_TXS_SLOT = word("miden::standards::auth::multisig::executed_transactions")

# The slot in this component's storage layout where procedure thresholds are stored.
# Map entries: PROC_ROOT => [proc_threshold, 0, 0, 0]
const PROC_THRESHOLD_ROOTS_SLOT = word("miden::standards::auth::multisig::procedure_thresholds")

# Executed Transaction Flag Constant
const IS_EXECUTED_FLAG = ONE_WORD

# ERRORS
# =================================================================================================

const ERR_TX_ALREADY_EXECUTED = "failed to approve multisig transaction as it was already executed"

const ERR_MALFORMED_MULTISIG_CONFIG = "number of approvers must be equal to or greater than threshold"

const ERR_ZERO_IN_MULTISIG_CONFIG = "number of approvers or threshold must not be zero"

const ERR_APPROVER_COUNTS_NOT_U32 = "initial and new number of approvers must be u32"

const ERR_NUM_APPROVERS_OR_SIGNER_INDEX_NOT_U32 = "number of approvers and signer index must be u32"

const ERR_SIGNER_INDEX_OUT_OF_BOUNDS = "signer index must be less than the number of approvers"

const ERR_PROC_THRESHOLD_NOT_U32 = "procedure threshold must be u32"

const ERR_NUM_APPROVERS_OR_PROC_THRESHOLD_NOT_U32 = "number of approvers and procedure threshold must be u32"

const ERR_PROC_THRESHOLD_EXCEEDS_NUM_APPROVERS = "procedure threshold exceeds new number of approvers"

const ERR_PROC_ROOT_NOT_IN_ACCOUNT = "procedure root is not one of the account's procedures"

const ERR_DUPLICATE_APPROVER_PUBLIC_KEY = "duplicate approver public keys are not allowed"

const ERR_EIP712_REQUIRES_ECDSA = "EIP-712 transaction-summary signatures require ecdsa_k256_keccak"

const ERR_EIP712_INVALID_SIGNATURE_LENGTH = "EIP-712 signature advice value must contain exactly 32 field elements"

# PUBLIC INTERFACE
# =================================================================================================

#! Update threshold config, add & remove approvers, and update the approver scheme ids
#!
#! Note: per-procedure threshold overrides in \`PROC_THRESHOLD_ROOTS_SLOT\` are NOT re-scaled by this
#! procedure. They are absolute signature counts, not ratios, and the only cross-check is
#! \`assert_proc_thresholds_lte_num_approvers\`, which enforces \`override <= num_approvers\`. Growing
#! the signer set therefore leaves every override unchanged and silently lowers its effective signing
#! ratio (e.g. a 2-of-2 override becomes 2-of-N). To preserve the intended security level, operators
#! must re-evaluate and, where appropriate, raise the affected overrides via \`set_procedure_threshold\`
#! in the same transaction that grows the signer set; this procedure neither performs nor prompts it.
#!
#! Security: like editing an override, this is gated only at the default threshold and can be used
#! to weaken a stricter setup. See the \`AuthMultisig\` Rust type's documentation.
#!
#! Inputs:
#!   Operand stack: [MULTISIG_CONFIG_HASH, pad(12)]
#!   Advice map: {
#!     MULTISIG_CONFIG_HASH =>
#!     [
#!       CONFIG,
#!       PUB_KEY_N, SCHEME_ID_N,
#!       PUB_KEY_N-1, SCHEME_ID_N-1,
#!       ...,
#!       PUB_KEY_0, SCHEME_ID_0
#!     ]
#!   }
#! Outputs:
#!   Operand stack: []
#!
#! Where:
#! - MULTISIG_CONFIG_HASH is the hash of the threshold,
#!   new public key vector, and the corresponding scheme identifiers
#! - MULTISIG_CONFIG is [threshold, num_approvers, 0, 0]
#! - PUB_KEY_i is the public key of the i-th signer
#! - SCHEME_ID_i is the signature scheme id of the i-th signer
#!
#! Locals:
#! 0: new_num_of_approvers
#! 1: init_num_of_approvers
#!
#! Invocation: call
@locals(2)
@account_procedure
pub proc update_signers_and_threshold(multisig_config_hash: word)
    # The signer configuration is read from the advice provider without an inline hash check. Every
    # value written below via set_map_item is folded into ACCOUNT_DELTA_COMMITMENT, which is part of
    # the TX_SUMMARY_COMMITMENT the current signers sign, so a substituted configuration produces a
    # different delta commitment and thus a summary the current signers never signed. The same
    # applies to the per-signer loads in the loop below.
    adv.push_mapval
    # => [MULTISIG_CONFIG_HASH, pad(12)]

    adv_loadw
    # => [MULTISIG_CONFIG, pad(12)]

    # store new_num_of_approvers for later
    dup.1 loc_store.NEW_NUM_OF_APPROVERS_LOC
    # => [MULTISIG_CONFIG, pad(12)]

    dup dup.2
    # => [num_approvers, threshold, MULTISIG_CONFIG, pad(12)]

    # make sure that the threshold is reachable with the number of approvers
    exec.assert_threshold_is_reachable
    # => [MULTISIG_CONFIG, pad(12)]

    dup dup.2
    # => [num_approvers, threshold, MULTISIG_CONFIG, pad(12)]

    # make sure that threshold or num_approvers are not zero
    eq.0 assertz.err=ERR_ZERO_IN_MULTISIG_CONFIG
    eq.0 assertz.err=ERR_ZERO_IN_MULTISIG_CONFIG
    # => [MULTISIG_CONFIG, pad(12)]

    # MULTISIG_CONFIG is [threshold, num_approvers, 0, 0], so num_approvers is at index 1
    dup.1
    # => [num_approvers, MULTISIG_CONFIG, pad(12)]

    # make sure that all existing procedure threshold overrides remain reachable
    exec.assert_proc_thresholds_lte_num_approvers
    # => [MULTISIG_CONFIG, pad(12)]

    push.THRESHOLD_CONFIG_SLOT[0..2]
    # => [config_slot_suffix, config_slot_prefix, MULTISIG_CONFIG, pad(12)]

    exec.native_account::set_item
    # => [OLD_THRESHOLD_CONFIG, pad(12)]

    # store init_num_of_approvers for later
    drop loc_store.INIT_NUM_OF_APPROVERS_LOC drop drop
    # => [pad(12)]

    loc_load.NEW_NUM_OF_APPROVERS_LOC
    # => [num_approvers]

    # num_approvers was already asserted non-zero above, so enter the loop unconditionally
    push.1
    while.true
        sub.1
        # => [i-1, pad(12)]

        dup exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, i-1, pad(12)]

        padw adv_loadw
        # => [PUB_KEY, APPROVER_MAP_KEY, i-1, pad(12)]

        swapw
        # => [APPROVER_MAP_KEY, PUB_KEY, i-1, pad(12)]

        push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
        # => [pub_key_slot_suffix, pub_key_slot_prefix, APPROVER_MAP_KEY, PUB_KEY, i-1, pad(12)]

        exec.native_account::set_map_item
        # => [OLD_VALUE, i-1, pad(12)]

        # override OLD_VALUE with SCHEME_ID_WORD
        adv_loadw
        # => [SCHEME_ID_WORD, i-1, pad(12)]

        # validate the scheme id word is in a correct form
        exec.auth::signature::assert_supported_scheme_word
        # => [SCHEME_ID_WORD, i-1, pad(12)]

        dup.4 exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, SCHEME_ID_WORD, i-1, pad(12)]

        push.APPROVER_SCHEME_ID_SLOT[0..2]
        # => [scheme_id_slot_id_suffix, scheme_id_slot_id_prefix, APPROVER_MAP_KEY, SCHEME_ID_WORD, i-1, pad(12)]

        exec.native_account::set_map_item
        # => [OLD_VALUE, i-1, pad(12)]

        dropw
        # => [i-1, pad(12)]

        dup neq.0
        # => [is_non_zero, i-1, pad(12)]
    end
    # => [pad(13)]

    drop
    # => [pad(12)]

    # assert all approver public keys are unique.
    loc_load.NEW_NUM_OF_APPROVERS_LOC
    exec.assert_unique_approver_public_keys
    # => [pad(12)]

    # compare initial vs current multisig config

    # load init_num_of_approvers & new_num_of_approvers
    loc_load.NEW_NUM_OF_APPROVERS_LOC loc_load.INIT_NUM_OF_APPROVERS_LOC
    # => [init_num_of_approvers, new_num_of_approvers, pad(12)]

    exec.cleanup_pubkey_and_scheme_id_mapping
    # => [pad(12)]
end

#! Returns the current threshold and num_approvers from \`THRESHOLD_CONFIG_SLOT\`.
#!
#! Inputs:  [pad(16)]
#! Outputs: [default_threshold, num_approvers, pad(14)]
#!
#! Invocation: call
@account_procedure
pub proc get_threshold_and_num_approvers
    exec.get_current_threshold_and_num_approvers
    # => [default_threshold, num_approvers, pad(16)]

    # truncate the stack
    movup.2 drop movup.2 drop
    # => [default_threshold, num_approvers, pad(14)]
end

#! Sets or clears a per-procedure threshold override.
#!
#! Security: a raised override is only as strong as the default threshold, since lowering it is
#! gated only at the default. See the \`AuthMultisig\` Rust type's documentation.
#!
#! Inputs: [proc_threshold, PROC_ROOT]
#! Outputs: []
#!
#! Where:
#! - PROC_ROOT is the root of the account procedure whose override is being updated.
#! - proc_threshold is the override threshold to set.
#!   - if proc_threshold == 0, override is cleared and the default threshold applies.
#!   - if proc_threshold > 0, it must be <= current num_approvers.
#!
#! Panics if:
#! - proc_threshold is not a u32 value.
#! - current num_approvers is not a u32 value.
#! - proc_threshold > current num_approvers.
#! - PROC_ROOT is not one of the account's procedures.
#!
#! Invocation: call
@account_procedure
pub proc set_procedure_threshold
    exec.get_current_threshold_and_num_approvers
    # => [default_threshold, num_approvers, proc_threshold, PROC_ROOT]

    drop
    # => [num_approvers, proc_threshold, PROC_ROOT]

    dup.1 swap
    # => [num_approvers, proc_threshold, proc_threshold, PROC_ROOT]

    u32assert2.err=ERR_NUM_APPROVERS_OR_PROC_THRESHOLD_NOT_U32
    u32gt assertz.err=ERR_PROC_THRESHOLD_EXCEEDS_NUM_APPROVERS
    # => [proc_threshold, PROC_ROOT]

    movdn.4 dupw
    # => [PROC_ROOT, PROC_ROOT, proc_threshold]

    exec.active_account::has_procedure
    assert.err=ERR_PROC_ROOT_NOT_IN_ACCOUNT
    # => [PROC_ROOT, proc_threshold]

    movup.4
    # => [proc_threshold, PROC_ROOT]

    # Store [proc_threshold, 0, 0, 0] = PROC_THRESHOLD_WORD, where proc_threshold == 0 acts as clear.
    push.0.0.0
    movup.3
    swapw
    # => [PROC_ROOT, PROC_THRESHOLD_WORD]

    push.PROC_THRESHOLD_ROOTS_SLOT[0..2]
    # => [proc_roots_slot_suffix, proc_roots_slot_prefix, PROC_ROOT, PROC_THRESHOLD_WORD]

    exec.native_account::set_map_item
    # => [OLD_PROC_THRESHOLD_WORD]

    dropw
    # => []
end

#! Returns signer public key at index i
#!
#! Reads the initial account state: the returned signer reflects the approver set at the start of
#! the transaction, not any updates made earlier in the same transaction.
#!
#! Inputs:  [index, pad(15)]
#! Outputs: [PUB_KEY, scheme_id, pad(11)]
#!
#! Panics if:
#! - index is not a u32 value.
#! - index is greater than or equal to the number of approvers.
#!
#! Invocation: call
@account_procedure
pub proc get_signer_at
    # Bounds check: index must be < num_approvers
    dup exec.get_initial_threshold_and_num_approvers drop
    # => [num_approvers, index, index]

    u32assert2.err=ERR_NUM_APPROVERS_OR_SIGNER_INDEX_NOT_U32
    u32lt assert.err=ERR_SIGNER_INDEX_OUT_OF_BOUNDS
    # => [index]

    dup
    # => [index, index]

    exec.signature::create_approver_map_key
    # => [APPROVER_MAP_KEY, index]

    push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
    # => [pub_key_slot_suffix, pub_key_slot_prefix, APPROVER_MAP_KEY, index]

    exec.native_account::get_initial_map_item
    # => [PUB_KEY, index]

    movup.4
    # => [index, PUB_KEY]

    exec.signature::create_approver_map_key
    # => [APPROVER_MAP_KEY, PUB_KEY]

    push.APPROVER_SCHEME_ID_SLOT[0..2]
    # => [scheme_id_slot_suffix, scheme_id_slot_prefix, APPROVER_MAP_KEY, PUB_KEY]

    exec.native_account::get_initial_map_item
    # => [[scheme_id, 0, 0, 0], PUB_KEY]

    movdn.7 drop drop drop
    # => [PUB_KEY, scheme_id, pad(15)]

    # truncate the stack
    repeat.4 movup.5 drop end
    # => [PUB_KEY, scheme_id, pad(11)]
end

#! Returns 1 if PUB_KEY is a signer, else 0.
#!
#! Reads the initial account state: the result reflects the approver set at the start of the
#! transaction, not any updates made earlier in the same transaction.
#!
#! Inputs:  [PUB_KEY, pad(12)]
#! Outputs: [is_signer, pad(15)]
#! Locals:
#! 0: is_signer_found
#! 1: current_signer_index
#!
#! Invocation: call
@locals(2)
@account_procedure
pub proc is_signer(pub_key: word) -> felt
    # initialize is_signer_found = false
    push.0 loc_store.IS_SIGNER_FOUND_LOC
    # => [PUB_KEY]

    exec.get_initial_threshold_and_num_approvers
    # => [threshold, num_approvers, PUB_KEY]

    drop
    # => [num_approvers, PUB_KEY]

    dup neq.0
    # => [has_remaining_signers, num_approvers, PUB_KEY]

    while.true
        # => [i, PUB_KEY]

        sub.1
        # => [i-1, PUB_KEY]

        # store i-1 for this loop iteration before map lookup
        dup loc_store.CURRENT_SIGNER_INDEX_LOC
        # => [i-1, PUB_KEY]

        exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, PUB_KEY]

        push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
        # => [pub_key_slot_suffix, pub_key_slot_prefix, APPROVER_MAP_KEY, PUB_KEY]

        exec.native_account::get_initial_map_item
        # => [CURRENT_PUB_KEY, PUB_KEY]

        dupw.1 exec.word::eq
        # => [is_pub_key_match, PUB_KEY]

        loc_store.IS_SIGNER_FOUND_LOC
        # => [PUB_KEY]

        loc_load.CURRENT_SIGNER_INDEX_LOC
        # => [i-1, PUB_KEY]

        dup neq.0
        # => [has_remaining_signers, i-1, PUB_KEY]

        loc_load.IS_SIGNER_FOUND_LOC not
        # => [!is_signer_found, has_remaining_signers, i-1, PUB_KEY]

        and
        # => [should_loop, i-1, PUB_KEY]
    end

    drop dropw
    # => [pad(16)]

    loc_load.IS_SIGNER_FOUND_LOC
    # => [is_signer, pad(16)]

    # truncate the stack
    swap drop
    # => [is_signer, pad(15)]
end

# PUBLIC HELPERS
# =================================================================================================

#! Remove old approver public keys and the corresponding scheme ids from the approver public key and
#! scheme id mappings.
#!
#! This procedure clears the approver entries in the range [new_num_of_approvers,
#! init_num_of_approvers) from APPROVER_PUBLIC_KEYS_SLOT and APPROVER_SCHEME_ID_SLOT. It does not
#! touch THRESHOLD_CONFIG_SLOT or PROC_THRESHOLD_ROOTS_SLOT.
#!
#! Caller contract: before calling this, the caller must have already updated THRESHOLD_CONFIG_SLOT
#! so that the threshold is still reachable with the reduced signer set, i.e. threshold <=
#! new_num_of_approvers. Otherwise the account is left with a threshold that no remaining quorum can
#! reach, making it permanently unable to authenticate. In-tree this is guaranteed by
#! \`update_signers_and_threshold\`, which calls \`assert_threshold_is_reachable\` before this procedure.
#!
#! Inputs: [init_num_of_approvers, new_num_of_approvers]
#! Outputs: []
#!
#! Where:
#! - init_num_of_approvers is the original number of approvers before the update
#! - new_num_of_approvers is the new number of approvers after the update
#!
#! Panics if:
#! - init_num_of_approvers or new_num_of_approvers is not a u32 value.
#!
#! Invocation: exec
pub proc cleanup_pubkey_and_scheme_id_mapping(init_num_of_approvers: u32, new_num_of_approvers: u32)
    dup.1 dup.1
    u32assert2.err=ERR_APPROVER_COUNTS_NOT_U32
    u32lt
    # => [should_loop, i = init_num_of_approvers, new_num_of_approvers]

    while.true
        # => [i, new_num_of_approvers]

        sub.1
        # => [i-1, new_num_of_approvers]

        # clear scheme id at APPROVER_MAP_KEY(i-1)
        dup exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, i-1, new_num_of_approvers]

        padw swapw
        # => [APPROVER_MAP_KEY, EMPTY_WORD, i-1, new_num_of_approvers]

        push.APPROVER_SCHEME_ID_SLOT[0..2]
        # => [scheme_id_slot_suffix, scheme_id_slot_prefix, APPROVER_MAP_KEY, EMPTY_WORD, i-1, new_num_of_approvers]

        exec.native_account::set_map_item
        # => [OLD_VALUE, i-1, new_num_of_approvers]

        dropw
        # => [i-1, new_num_of_approvers]

        # clear public key at APPROVER_MAP_KEY(i-1)
        dup exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, i-1, new_num_of_approvers]

        padw swapw
        # => [APPROVER_MAP_KEY, EMPTY_WORD, i-1, new_num_of_approvers]

        push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
        # => [pub_key_slot_suffix, pub_key_slot_prefix, APPROVER_MAP_KEY, EMPTY_WORD, i-1, new_num_of_approvers]

        exec.native_account::set_map_item
        # => [OLD_VALUE, i-1, new_num_of_approvers]

        dropw
        # => [i-1, new_num_of_approvers]

        dup.1 dup.1
        u32lt
        # => [should_loop, i-1, new_num_of_approvers]
    end

    drop drop
end

#! Asserts the threshold is reachable with the given number of approvers, i.e. threshold is not
#! greater than num_approvers.
#!
#! Inputs:  [num_approvers, threshold]
#! Outputs: []
#!
#! Panics if:
#! - num_approvers or threshold is not a u32 value.
#! - threshold > num_approvers.
#!
#! Invocation: exec
pub proc assert_threshold_is_reachable
    u32assert2.err=ERR_MALFORMED_MULTISIG_CONFIG
    u32gt assertz.err=ERR_MALFORMED_MULTISIG_CONFIG
end

#! Asserts that the \`num_approvers\` public keys currently stored in APPROVER_PUBLIC_KEYS_SLOT are
#! pairwise distinct, reverting on the first duplicate.
#!
#! Reads the current account state, so it validates the keys just written by the caller.
#!
#! Inputs:  [num_approvers]
#! Outputs: []
#! Panics if:
#! - any two approver public keys are equal.
#!
#! Cost: O(num_approvers^2) map reads; num_approvers is small for a multisig.
#!
#! Invocation: exec
@locals(2)
pub proc assert_unique_approver_public_keys(num_approvers: u32)
    dup neq.0
    # => [outer_continue, num_approvers]
    while.true
        sub.1
        # => [i]

        dup loc_store.UNIQUE_OUTER_INDEX_LOC
        # => [i]

        # read PK_i from the current state
        dup exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, i]

        push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
        exec.active_account::get_map_item
        # => [PK_I, i]

        movup.4
        # => [i, PK_I]

        dup neq.0
        # => [inner_continue, i, PK_I]
        while.true
            sub.1
            # => [j, PK_I]

            dup loc_store.UNIQUE_INNER_INDEX_LOC
            exec.signature::create_approver_map_key
            # => [APPROVER_MAP_KEY, PK_I]

            push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
            exec.active_account::get_map_item
            # => [PK_J, PK_I]

            # assert PK_I != PK_J
            dupw.1 exec.word::eq
            # => [is_equal, PK_I]

            assertz.err=ERR_DUPLICATE_APPROVER_PUBLIC_KEY
            # => [PK_I]

            loc_load.UNIQUE_INNER_INDEX_LOC
            # => [j, PK_I]

            dup neq.0
            # => [inner_continue, j, PK_I]
        end
        # => [0, PK_I]

        drop dropw
        # => []

        loc_load.UNIQUE_OUTER_INDEX_LOC
        # => [i]

        dup neq.0
        # => [outer_continue, i]
    end

    drop
    # => []
end

#! Returns the initial threshold and num_approvers from \`THRESHOLD_CONFIG_SLOT\`.
#!
#! Inputs: []
#! Outputs: [default_threshold, num_approvers]
#!
#! Invocation: exec
pub proc get_initial_threshold_and_num_approvers
    push.THRESHOLD_CONFIG_SLOT[0..2]
    exec.native_account::get_initial_item
    # => [default_threshold, num_approvers, 0, 0]

    movup.2 drop movup.2 drop
    # => [default_threshold, num_approvers]
end

#! Records the transaction as executed and asserts it was not already executed, providing replay
#! protection and finalizing multisig authentication.
#!
#! Writes IS_EXECUTED_FLAG into EXECUTED_TXS_SLOT keyed by MSG via set_map_item, then asserts the
#! slot did not already hold the flag.
#!
#! Inputs:  [MSG]
#! Outputs: []
#!
#! Panics if:
#! - the same transaction has already been executed
#!
#! Invocation: exec
pub proc record_and_assert_new_tx(msg: word)
    push.IS_EXECUTED_FLAG
    # => [[is_executed, 0, 0, 0], MSG]

    swapw
    # => [TX_SUMMARY_COMMITMENT, IS_EXECUTED_FLAG]

    push.EXECUTED_TXS_SLOT[0..2]
    # => [txs_slot_suffix, txs_slot_prefix, MSG, IS_EXECUTED_FLAG]

    # Set the key value pair in the map to mark transaction as executed
    exec.native_account::set_map_item
    # => [[is_executed, 0, 0, 0]]

    movdn.3 drop drop drop
    # => [is_executed]

    assertz.err=ERR_TX_ALREADY_EXECUTED
    # => []
end

#! Authenticates a transaction with threshold signatures.
#!
#! Supported schemes:
#! - 1 => ecdsa_k256_keccak
#! - 2 => falcon512_poseidon2
#!
#! Inputs:
#!   Operand stack: [user_param0, user_param1, user_param2, user_param3, user_param4, user_param5,
#!                   user_param6]
#!   Advice map: {
#!     H(PK_COMM, MSG): RAW_SIGNATURE,
#!     H(H(PK_COMM, MSG), [0x32313745; 4]): EIP712_ECDSA_SIGNATURE
#!   }
#! Outputs:
#!   Operand stack: [TX_SUMMARY_COMMITMENT]
#!
#! Where:
#! - H is Poseidon2.
#! - PK_COMM is an approver's public-key commitment.
#! - MSG is the transaction message being signed.
#! - User parameters are folded into MSG without assigning them semantics.
#! - Raw advice takes precedence when both keys are present.
#! - A wrapper must call \`record_and_assert_new_tx\`; this procedure does not record the summary.
#!
#! Panics if:
#! - The signature threshold is not met.
#! - An EIP-712 entry belongs to a non-ECDSA approver or does not contain 32 field elements.
#!
#! Invocation: exec
pub proc auth_tx(user_params: [felt; 7])
    exec.native_account::incr_nonce drop
    # => [user_params(7)]

    # ------ Computing transaction summary ------

    exec.auth::create_tx_summary
    # => [ACCOUNT_DELTA_COMMITMENT, INPUT_NOTES_COMMITMENT, OUTPUT_NOTES_COMMITMENT, BLOCK_COMMITMENT, PARAMS_HEAD, PARAMS_TAIL]

    # the commitment to the tx summary is the message that is signed; the preimage is inserted
    # into the advice map for extraction by the host
    exec.auth::hash_and_insert_tx_summary
    # => [TX_SUMMARY_COMMITMENT]

    # ------ Verifying approver signatures ------

    exec.get_initial_threshold_and_num_approvers
    # => [default_threshold, num_of_approvers, TX_SUMMARY_COMMITMENT]

    movdn.5
    # => [num_of_approvers, TX_SUMMARY_COMMITMENT, default_threshold]

    exec.verify_approver_signatures
    # => [num_verified_signatures, TX_SUMMARY_COMMITMENT, default_threshold]

    # ------ Checking threshold is >= num_verified_signatures ------

    movup.5
    # => [default_threshold, num_verified_signatures, TX_SUMMARY_COMMITMENT]

    exec.compute_transaction_threshold
    # => [transaction_threshold, num_verified_signatures, TX_SUMMARY_COMMITMENT]

    u32assert2 u32lt
    # => [is_unauthorized, TX_SUMMARY_COMMITMENT]

    # If signatures are non-existent the tx will fail here.
    if.true
        emit.AUTH_UNAUTHORIZED_EVENT
        push.0 assert.err="insufficient number of signatures"
    end

    # TX_SUMMARY_COMMITMENT is returned so wrappers can run optional checks
    # (e.g. guardian verification) before replay-protection finalization.
    # => [TX_SUMMARY_COMMITMENT]
end

# Verifies each approver at most once. Raw advice takes precedence; EIP-712 advice is accepted only
# for ECDSA approvers under its domain-separated key.
#
# Inputs:  [num_of_approvers, MSG]
# Outputs: [num_verified_signatures, MSG]
@locals(1)
proc verify_approver_signatures
    push.0 loc_store.SUCCESSFUL_VERIFICATIONS_LOC
    # => [num_of_approvers, MSG]

    dup neq.0
    while.true
        # => [i, MSG]

        sub.1 dup
        # => [signer_idx, signer_idx, MSG]

        exec.signature::create_approver_map_key
        # => [APPROVER_MAP_KEY, signer_idx, MSG]

        push.APPROVER_PUBLIC_KEYS_SLOT[0..2]
        exec.native_account::get_initial_map_item
        # => [PK_COMM, signer_idx, MSG]

        movup.4 movdn.8
        # => [PK_COMM, MSG, signer_idx]

        # Check the existing raw-signature advice key first.
        dupw.1 dupw.1
        exec.poseidon2::merge
        # => [RAW_SIG_KEY, PK_COMM, MSG, signer_idx]

        adv.has_mapkey
        dropw
        adv_push
        # => [has_raw_signature, PK_COMM, MSG, signer_idx]

        if.true
            dupw.1
            # => [MSG, PK_COMM, MSG, signer_idx]

            emit.AUTH_REQUEST_EVENT
            swapw
            # => [PK_COMM, MSG, MSG, signer_idx]

            dup.12 exec.signature::create_approver_map_key
            push.APPROVER_SCHEME_ID_SLOT[0..2]
            exec.native_account::get_initial_map_item
            # => [[scheme_id, 0, 0, 0], PK_COMM, MSG, MSG, signer_idx]

            movdn.3 drop drop drop
            # OS => [scheme_id, PK_COMM, MSG, MSG, signer_idx]
            # AS => [SIGNATURE]

            exec.signature::verify_signature_by_scheme
            # => [MSG, signer_idx]

            loc_load.SUCCESSFUL_VERIFICATIONS_LOC add.1
            loc_store.SUCCESSFUL_VERIFICATIONS_LOC
            # => [MSG, signer_idx]
        else
            # Check the domain-separated EIP-712 signature key.
            dupw.1 dupw.1
            exec.poseidon2::merge
            exec.eip712::extend_signature_key
            # => [EIP712_SIG_KEY, PK_COMM, MSG, signer_idx]

            adv.has_mapkey
            adv_push
            # => [has_eip712_signature, EIP712_SIG_KEY, PK_COMM, MSG, signer_idx]

            if.true
                # The EIP-712 witness is loaded directly, so validate its length first.
                adv.push_mapval_count
                adv_push
                eq.32 assert.err=ERR_EIP712_INVALID_SIGNATURE_LENGTH
                # => [EIP712_SIG_KEY, PK_COMM, MSG, signer_idx]

                adv.push_mapval
                dropw
                # OS => [PK_COMM, MSG, signer_idx]
                # AS => [SIGNATURE]

                dupw.1 swapw
                # => [PK_COMM, MSG, MSG, signer_idx]

                dup.12 exec.signature::create_approver_map_key
                push.APPROVER_SCHEME_ID_SLOT[0..2]
                exec.native_account::get_initial_map_item
                # => [[scheme_id, 0, 0, 0], PK_COMM, MSG, MSG, signer_idx]

                movdn.3 drop drop drop
                # => [scheme_id, PK_COMM, MSG, MSG, signer_idx]

                eq.ECDSA_K256_KECCAK_SCHEME_ID
                assert.err=ERR_EIP712_REQUIRES_ECDSA
                # => [PK_COMM, MSG, MSG, signer_idx]

                exec.eip712::verify_transaction_summary
                # => [MSG, signer_idx]

                loc_load.SUCCESSFUL_VERIFICATIONS_LOC add.1
                loc_store.SUCCESSFUL_VERIFICATIONS_LOC
                # => [MSG, signer_idx]
            else
                dropw dropw
                # => [MSG, signer_idx]
            end
        end

        movup.4
        # => [signer_idx, MSG]

        dup neq.0
        # => [should_continue, signer_idx, MSG]
    end

    drop
    # => [MSG]

    loc_load.SUCCESSFUL_VERIFICATIONS_LOC
    # => [num_verified_signatures, MSG]
end

# HELPER PROCEDURES
# =================================================================================================

#! Asserts that all configured per-procedure threshold overrides are less than or equal to
#! number of approvers.
#!
#! Inputs:  [num_approvers]
#! Outputs: []
#! Panics if:
#! - any configured procedure threshold is not a u32 value.
#! - any configured procedure threshold exceeds num_approvers.
proc assert_proc_thresholds_lte_num_approvers(num_approvers: u32)
    exec.active_account::get_num_procedures
    # => [num_procedures, num_approvers]

    # num_procedures is always >= MIN_NUM_PROCEDURES (2), so enter the loop unconditionally
    push.1
    # => [should_continue, num_procedures, num_approvers]
    while.true
        sub.1 dup
        # => [num_procedures-1, num_procedures-1, num_approvers]

        exec.active_account::get_procedure_root
        # => [PROC_ROOT, num_procedures-1, num_approvers]

        push.PROC_THRESHOLD_ROOTS_SLOT[0..2]
        # => [proc_roots_slot_suffix, proc_roots_slot_prefix, PROC_ROOT, num_procedures-1, num_approvers]

        # Use the *current* policy state, not the initial one; otherwise a \`set_proc_threshold\`
        # call earlier in the same transaction that raised a threshold above the new num_approvers
        # would be missed and the multisig could end up with an unreachable threshold.
        exec.active_account::get_map_item
        # => [[proc_threshold, 0, 0, 0], num_procedures-1, num_approvers]

        movdn.3 drop drop drop
        # => [proc_threshold, num_procedures-1, num_approvers]

        dup.2
        # => [num_approvers, proc_threshold, num_procedures-1, num_approvers]

        u32assert2.err=ERR_PROC_THRESHOLD_NOT_U32
        u32gt assertz.err=ERR_PROC_THRESHOLD_EXCEEDS_NUM_APPROVERS
        # => [num_procedures-1, num_approvers]

        dup neq.0
        # => [should_continue, num_procedures-1, num_approvers]
    end
    # => [num_procedures-1, num_approvers]

    drop drop
    # => []
end

# Computes the effective transaction threshold based on called procedures and per-procedure
# overrides stored in PROC_THRESHOLD_ROOTS_SLOT. Falls back to default_threshold if no
# overrides apply.
#
# Each called non-auth procedure contributes a threshold to a max accumulator:
# - if the procedure has a stored override, its override value is the contribution.
# - if the procedure has no override, \`default_threshold\` is the contribution so a procedure
#   without a policy cannot be authorized at a lower threshold by being called alongside a
#   low-override procedure (e.g. \`receive_asset\` configured at 1) in the same transaction.
#
# The auth procedure (procedure index 0) is skipped — it is the auth flow itself, not a
# user-callable account procedure, and counting it would make \`transaction_threshold\` always
# include \`default_threshold\`.
#
# When no non-auth procedure was called, \`transaction_threshold\` stays 0 and is reverted to
# \`default_threshold\` at the end.
#
#! Inputs:  [default_threshold]
#! Outputs: [transaction_threshold]
@locals(1)
proc compute_transaction_threshold(default_threshold: u32) -> u32
    # 1. initialize transaction_threshold = 0
    # 2. iterate through all non-auth account procedures
    #   a. check if the procedure was called during the transaction
    #   b. if called, get the override threshold of that procedure from the config map
    #   c. if the procedure has no override (proc_threshold == 0), contribute default_threshold
    #      instead so the unpolicied call is still constrained
    #   d. if contribution > transaction_threshold, set transaction_threshold = contribution
    # 3. if transaction_threshold == 0 at the end (no non-auth proc was called), revert to
    #    using default_threshold

    # store default_threshold for later
    loc_store.DEFAULT_THRESHOLD_LOC
    # => []

    # 1. initialize transaction_threshold = 0
    push.0
    # => [transaction_threshold]

    # get the number of account procedures
    exec.active_account::get_num_procedures
    # => [num_procedures, transaction_threshold]

    # 2. iterate through all account procedures
    # num_procedures is always >= MIN_NUM_PROCEDURES (2), so enter the loop unconditionally
    push.1
    # => [should_continue, num_procedures, transaction_threshold]
    while.true
        sub.1
        # => [num_procedures-1, transaction_threshold]

        # Skip the auth procedure at index 0 — it is the auth flow itself, not a user-callable
        # account procedure. Counting it would make transaction_threshold always include
        # default_threshold and break the override-down semantic for single-proc transactions.
        dup neq.0
        # => [is_non_auth, num_procedures-1, transaction_threshold]
        if.true
            # get procedure root of the procedure with index i
            dup exec.active_account::get_procedure_root dupw
            # => [PROC_ROOT, PROC_ROOT, num_procedures-1, transaction_threshold]

            # 2a. check if this procedure has been called in the transaction
            exec.native_account::was_procedure_called
            # => [was_called, PROC_ROOT, num_procedures-1, transaction_threshold]

            # if it has been called, compute and apply its threshold contribution
            if.true
                # => [PROC_ROOT, num_procedures-1, transaction_threshold]

                push.PROC_THRESHOLD_ROOTS_SLOT[0..2]
                # => [proc_roots_slot_suffix, proc_roots_slot_prefix, PROC_ROOT, num_procedures-1, transaction_threshold]

                # 2b. get the override proc_threshold of that procedure
                # if the procedure has no override threshold, the returned map item will be [0, 0, 0, 0]
                exec.native_account::get_initial_map_item
                # => [[proc_threshold, 0, 0, 0], num_procedures-1, transaction_threshold]

                movdn.3 drop drop drop
                # => [proc_threshold, num_procedures-1, transaction_threshold]

                # 2c. if the procedure has no override (proc_threshold == 0), contribute
                # default_threshold instead so the unpolicied call cannot be silently authorized
                # at a lower threshold by being called alongside a low-override procedure
                # (e.g. \`receive_asset\` configured at 1) in the same transaction.
                dup eq.0
                if.true
                    drop
                    loc_load.DEFAULT_THRESHOLD_LOC
                end
                # => [contribution, num_procedures-1, transaction_threshold]

                # 2d. transaction_threshold = max(transaction_threshold, contribution)
                movup.2 u32max
                # => [new_transaction_threshold, num_procedures-1]

                swap
                # => [num_procedures-1, new_transaction_threshold]
            # if it has not been called during this transaction, nothing to do, move to the next procedure
            else
                dropw
                # => [num_procedures-1, transaction_threshold]
            end
        end

        dup neq.0
        # => [should_continue, num_procedures-1, transaction_threshold]
    end

    drop
    # => [transaction_threshold]

    loc_load.DEFAULT_THRESHOLD_LOC
    # => [default_threshold, transaction_threshold]

    # 3. if no non-auth proc was called, transaction_threshold is 0; fall back to default_threshold
    dup.1 eq.0
    # => [is_zero, default_threshold, transaction_threshold]

    cdrop
    # => [effective_transaction_threshold]
end

#! Returns the current threshold and num_approvers from \`THRESHOLD_CONFIG_SLOT\`.
#!
#! This is the internal \`exec\` helper shared by internal callers and the public \`call\`
#! wrapper \`get_threshold_and_num_approvers\`.
#!
#! Inputs: []
#! Outputs: [default_threshold, num_approvers]
#!
#! Invocation: exec
proc get_current_threshold_and_num_approvers
    push.THRESHOLD_CONFIG_SLOT[0..2]
    exec.active_account::get_item
    # => [default_threshold, num_approvers, 0, 0]

    movup.2 drop movup.2 drop
    # => [default_threshold, num_approvers]
end
`;
