import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, '..');
const packageMasmDir = path.join(packageRoot, 'masm');
const generatedAccountDir = path.join(packageRoot, 'src', 'account');

const masmFiles = [
  {
    packagedPath: ['account_components', 'auth', 'guarded_multisig.masm'],
    exportName: 'GUARDED_MULTISIG_ACCOUNT_COMPONENT_MASM',
    generatedPath: ['masm', 'account-components', 'auth.ts'],
  },
  {
    packagedPath: ['libraries', 'auth', 'eip712.masm'],
    exportName: 'EIP712_LIBRARY_MASM',
    generatedPath: ['masm', 'libraries', 'auth.ts'],
  },
  {
    packagedPath: ['libraries', 'auth', 'eip712_multisig_v1_transaction_summary.masm'],
    exportName: 'EIP712_MULTISIG_V1_TRANSACTION_SUMMARY_LIBRARY_MASM',
    generatedPath: ['masm', 'libraries', 'auth.ts'],
  },
  {
    packagedPath: ['libraries', 'auth', 'signature.masm'],
    exportName: 'SIGNATURE_LIBRARY_MASM',
    generatedPath: ['masm', 'libraries', 'auth.ts'],
  },
  {
    packagedPath: ['libraries', 'auth', 'multisig.masm'],
    exportName: 'MULTISIG_LIBRARY_MASM',
    generatedPath: ['masm', 'libraries', 'auth.ts'],
  },
];

function fileExists(rootDir, pathSegments) {
  return existsSync(path.join(rootDir, ...pathSegments));
}

function resolveSourceDir() {
  const packagedAvailable = masmFiles.every(({ packagedPath }) =>
    fileExists(packageMasmDir, packagedPath),
  );
  if (packagedAvailable) {
    return packageMasmDir;
  }

  throw new Error(`unable to locate vendored MASM sources in '${packageMasmDir}'`);
}

function writeIfChanged(filePath, contents) {
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === contents) {
    return;
  }

  writeFileSync(filePath, contents, 'utf8');
}

function toTemplateLiteral(contents) {
  return `\`${contents
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')}\``;
}

const sourceDir = resolveSourceDir();
const masmSources = masmFiles.map(({ packagedPath, generatedPath, exportName }) => ({
  packagedPath,
  exportName,
  generatedPath,
  source: readFileSync(path.join(sourceDir, ...packagedPath), 'utf8'),
}));

const generatedModules = new Map();

for (const { generatedPath, exportName, source } of masmSources) {
  const key = generatedPath.join('/');
  const exportsSource = generatedModules.get(key) ?? [];
  exportsSource.push(`export const ${exportName} = ${toTemplateLiteral(source)};`);
  generatedModules.set(key, exportsSource);
}

for (const [generatedPath, exportsSource] of generatedModules.entries()) {
  const destination = path.join(generatedAccountDir, ...generatedPath.split('/'));
  const generatedSource = `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

${exportsSource.join('\n\n')}
`;
  mkdirSync(path.dirname(destination), { recursive: true });
  writeIfChanged(destination, generatedSource);
}

writeIfChanged(
  path.join(generatedAccountDir, 'masm', 'index.ts'),
  `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export * from './account-components/auth.js';
export * from './libraries/auth.js';
`,
);

writeIfChanged(
  path.join(generatedAccountDir, 'masm.ts'),
  `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export * from './masm/index.js';
`,
);
